env:
  browser: true
  es6: true
  commonjs: true
  node: true
  jest: true
parserOptions:
  sourceType: 'module'
  ecmaVersion: 10
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: 'detect'
plugins:
  - 'react-hooks'
  - 'react'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  # Prettier overrides
  - 'prettier'
  - 'prettier/react'
rules:
  react/prop-types: off
  no-var: error
  prefer-const: error
  no-unused-vars: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
